# Generated by Django 6.1.1 on 2026-10-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
